import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.ApplicationFrame;
import org.jfree.ui.RefineryUtilities;

public class BarAvalanche extends javax.swing.JFrame {

    /**
     * Creates new form BarAvalanche
     */
    
    public BarAvalanche() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
    }
    public  String dd = null;
    public  String i= null;
    public  String da = null;
    
    
public BarAvalanche(String applicationTitle,String chartTitle,String death,String inju, String dam){
    super(applicationTitle);
    dd=death;
    i=inju;
   da=dam;
    JFreeChart barChart = ChartFactory.createBarChart(chartTitle, "DEATH", "KILLED", createDataset(), PlotOrientation.VERTICAL,true,true,false);
    ChartPanel chartPanel = new ChartPanel(barChart);
    chartPanel.setPreferredSize(new java.awt.Dimension(560,367));
    setContentPane(chartPanel);

}
private CategoryDataset createDataset(){
    final String Avalanche = "AVALANCHE";
    final String Tornado = "TORNADO";
    final String landslide = "LANDSLIDE";
    final String death = "Death";
    final String injured = "Injured";
    final String damages = "Damages";
    final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    dataset.addValue(800,Avalanche,death);
     dataset.addValue(500000,Avalanche,injured);
      dataset.addValue(1543256,Avalanche,damages);
    return dataset;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarAvalanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarAvalanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarAvalanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarAvalanche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
  
  BarAvalanche Chart = new BarAvalanche("DISASTER REPORT","DEATH TOLL","5000","7000","3000000");
  RefineryUtilities.centerFrameOnScreen(Chart);
  Chart.setVisible(true);
  
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
