
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ponth
 */
public class BLIZZARD extends javax.swing.JFrame {

    /**
     * Creates new form BLIZZARD
     */
    public BLIZZARD() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        //JoptionPane.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mental = new javax.swing.JTextField();
        SNOW = new javax.swing.JTextField();
        jSpinField1 = new com.toedter.components.JSpinField();
        jScrollPane1 = new javax.swing.JScrollPane();
        commu = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        effect = new javax.swing.JTextArea();
        place = new javax.swing.JTextField();
        regi = new javax.swing.JTextField();
        damage = new javax.swing.JTextField();
        jSpinField2 = new com.toedter.components.JSpinField();
        jSpinField3 = new com.toedter.components.JSpinField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinField4 = new com.toedter.components.JSpinField();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(66, 33, 26));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(66, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLIZZARD - ATMOSPHERIC DISASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 19, 1470, -1));

        jButton3.setBackground(new java.awt.Color(66, 33, 26));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circled-chevron-left.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 33, 26)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 120));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(66, 33, 26));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(66, 0, 0));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FLOOD - AQUATIC DISASTER");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 19, 1470, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 120));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel3.setText("DATE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel4.setText("TOTAL POPULATION:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel5.setText("SNOW MEASURED:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel6.setText("DEATH RATE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 170, -1));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel7.setText("MISSING RATE:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 190, 30));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel8.setText("PLACE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel9.setText("REGIONS AFFECTED:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel10.setText("INJURED:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel11.setText("DAMAGES:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel12.setText("POWER OUTAGE:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel13.setText("EFFECTS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, -1, -1));

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel14.setText("COMMUNITY PARTICIPATION:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        mental.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        mental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentalActionPerformed(evt);
            }
        });
        jPanel1.add(mental, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 460, 210, -1));

        SNOW.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        SNOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNOWActionPerformed(evt);
            }
        });
        jPanel1.add(SNOW, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 210, -1));

        jSpinField1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSpinField1MouseDragged(evt);
            }
        });
        jPanel1.add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 300, 210, 30));

        commu.setColumns(20);
        commu.setRows(5);
        jScrollPane1.setViewportView(commu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 550, 90));

        effect.setColumns(20);
        effect.setRows(5);
        jScrollPane2.setViewportView(effect);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 500, 90));

        place.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeActionPerformed(evt);
            }
        });
        jPanel1.add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 160, 210, -1));

        regi.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        regi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regiActionPerformed(evt);
            }
        });
        jPanel1.add(regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 230, 210, -1));

        damage.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        damage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damageActionPerformed(evt);
            }
        });
        jPanel1.add(damage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 380, 210, -1));

        jSpinField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSpinField2FocusGained(evt);
            }
        });
        jPanel1.add(jSpinField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 210, 30));
        jPanel1.add(jSpinField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 210, 30));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 210, 30));
        jPanel1.add(jSpinField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton4.setBackground(new java.awt.Color(66, 33, 26));
        jButton4.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SUBMIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);

        jButton2.setBackground(new java.awt.Color(66, 33, 26));
        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 730, 550, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mentalActionPerformed

    private void SNOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNOWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNOWActionPerformed

    private void placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeActionPerformed

    private void regiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regiActionPerformed

    private void damageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_damageActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        con_disaster_frame con=new con_disaster_frame();
        con.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSpinField1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinField1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinField1MouseDragged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int spin3=jSpinField3.getValue();
        int spin1=jSpinField1.getValue();
        int spin2=jSpinField2.getValue();
        int spin4=jSpinField4.getValue();
      if(spin2==0)
        {
            JOptionPane.showMessageDialog(null," Total Population field is Empty");
        }
     
      
        else if(SNOW.getText().trim().isEmpty())
                       {
            JOptionPane.showMessageDialog(null,"Snow Measured is Empty");
        }
        else if(spin3==0)
        {
            JOptionPane.showMessageDialog(null,"Death Rate is Empty");
        }
        else if(spin4==0)
        {
            JOptionPane.showMessageDialog(null," Missing rate Field is Empty");
        }
        else if(commu.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null," Community participation is Empty");
        }
          else if(place.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Place Field is Empty");
        }
          else if(regi.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"region Affected Field is Empty");
        }
          else if(spin1==0)
                {
            JOptionPane.showMessageDialog(null,"Injury Field is Empty");
        }
          else if(damage.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Damage Field is Empty");
        }
          else if(mental.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Power Outage Field is Empty");
        }
         else if(effect.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Effects Field is Empty");
        }
        else
        {
        JOptionPane.showMessageDialog(rootPane,"SUCCESSFULLY REPORTED");
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setCalendar(null);
        jSpinField1.setValue(0);
        jSpinField2.setValue(0);
        jSpinField3.setValue(0);
        jSpinField4.setValue(0);
        
        SNOW.setText("");
        mental.setText("");
        place.setText("");
        regi.setText("");
        damage.setText("");
        effect.setText("");
        commu.setText("");
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSpinField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinField2FocusGained
        // TODO add your handling code here:
       //   JOptionPane.showInternalMessageDialog(rootPane, "HI MALINI");
          
    }//GEN-LAST:event_jSpinField2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BLIZZARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BLIZZARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BLIZZARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BLIZZARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BLIZZARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SNOW;
    private javax.swing.JTextArea commu;
    private javax.swing.JTextField damage;
    private javax.swing.JTextArea effect;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private com.toedter.components.JSpinField jSpinField3;
    private com.toedter.components.JSpinField jSpinField4;
    private javax.swing.JTextField mental;
    private javax.swing.JTextField place;
    private javax.swing.JTextField regi;
    // End of variables declaration//GEN-END:variables
}
