
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ponth
 */
public class earthuquakeForm extends javax.swing.JFrame {

    /**
     * Creates new form earthquake
     */
    public earthuquakeForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        e = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        c = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        d = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        sr = new javax.swing.JTextArea();
        ra = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSpinField1 = new com.toedter.components.JSpinField();
        jSpinField2 = new com.toedter.components.JSpinField();
        jSpinField3 = new com.toedter.components.JSpinField();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(66, 33, 26));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(66, 0, 0));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EARTHQUAKE - TERRESTRIAL DISASTER");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1540, -1));

        jButton4.setBackground(new java.awt.Color(66, 33, 26));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circled-chevron-left.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, -1, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 120));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel3.setText("DATE:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 59, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel4.setText("PLACE:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel5.setText("MISSING:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 251, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel6.setText("DEATH RATE:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 188, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel7.setText("EFFECTS:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 419, -1, -1));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel8.setText("SESIMIC RATE:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 328, -1, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel9.setText("INJURED:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 188, -1, -1));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel10.setText("REGIONS AFFECTED:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 119, -1, -1));

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel11.setText("TIME:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 59, -1, -1));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel12.setText("CAUSE:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 419, -1, -1));

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel13.setText("COMMUNITY PARTICIPATION:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 328, -1, -1));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel14.setText("DAMAGES:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 251, -1, -1));

        p.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        jPanel4.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 116, 158, -1));

        e.setColumns(20);
        e.setRows(5);
        jScrollPane1.setViewportView(e);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 458, 358, -1));

        c.setColumns(20);
        c.setRows(5);
        jScrollPane2.setViewportView(c);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 458, 371, -1));

        d.setColumns(20);
        d.setRows(5);
        jScrollPane3.setViewportView(d);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 248, 318, 50));

        sr.setColumns(20);
        sr.setRows(5);
        jScrollPane4.setViewportView(sr);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 318, 60));

        ra.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raActionPerformed(evt);
            }
        });
        jPanel4.add(ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 116, 158, -1));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1226, 328, 318, 65));
        jPanel4.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 59, 167, 33));
        jPanel4.add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 179, 160, 37));
        jPanel4.add(jSpinField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 184, 160, 37));
        jPanel4.add(jSpinField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 251, 160, 37));

        jButton3.setText("SUBMIT");
        jButton3.setBackground(new java.awt.Color(66, 33, 26));
        jButton3.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jButton2.setBackground(new java.awt.Color(66, 33, 26));
        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 550, 70));
        jPanel4.add(timePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 60, 190, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1690, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        con_disaster_frame con=new con_disaster_frame();
        con.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int spin3=jSpinField3.getValue();
        int spin1=jSpinField1.getValue();
        int spin2=jSpinField2.getValue();
      if(spin2==0)
        {
            JOptionPane.showMessageDialog(null," Death Rate field is Empty");
        }
     
      
        else if(p.getText().trim().isEmpty())
                       {
            JOptionPane.showMessageDialog(null,"Place is Empty");
        }
        else if(spin3==0)
        {
            JOptionPane.showMessageDialog(null,"Missing Rate is Empty");
        }
        
        else if(sr.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null," Seismic Rate is Empty");
        }
          else if(e.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Width Field is Empty");
        }
          else if(ra.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"region Affected Field is Empty");
        }
          else if(spin1==0)
                {
            JOptionPane.showMessageDialog(null,"Injury Field is Empty");
        }
          else if(d.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Damage Field is Empty");
        }
          else if(c.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Cause Field is Empty");
        }
         else if(e.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Effects Field is Empty");
        }
        else
        {
        JOptionPane.showMessageDialog(rootPane,"SUCCESSFULLY REPORTED");
                }
        JOptionPane.showMessageDialog(rootPane,"SUCCESSFULLY REPORTED");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(earthuquakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(earthuquakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(earthuquakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(earthuquakeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new earthuquakeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea c;
    private javax.swing.JTextArea d;
    private javax.swing.JTextArea e;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private com.toedter.components.JSpinField jSpinField3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField p;
    private javax.swing.JTextField ra;
    private javax.swing.JTextArea sr;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables
}
