
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ponth
 */
public class floodForm extends javax.swing.JFrame {

    /**
     * Creates new form flood
     */
    public floodForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        la = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        mr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        op = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dr = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        ra = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        d = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(66, 33, 26));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(66, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FLOOD - AQUATIC DISASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 19, 1470, -1));

        jButton4.setBackground(new java.awt.Color(66, 33, 26));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circled-chevron-left.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 120));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel2.setText("DATE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel3.setText("TOTAL POPULATION:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel4.setText("RAIN MEASURED:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel5.setText("DEATH RATE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 170, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel6.setText("MISSING RATE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 190, 30));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel7.setText("PLACE:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel8.setText("REGIONS AFFECTED:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel9.setText("INJURED:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel10.setText("DAMAGES:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel11.setText("PEOPLE MENTALITY:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel12.setText("OTHERS PLEASE SPECIFY:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, -1, -1));

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel13.setText("COMMUNITY PARTICIPATION:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        la.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        la.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laActionPerformed(evt);
            }
        });
        jPanel1.add(la, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 460, 210, -1));

        s.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        jPanel1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 210, -1));

        mr.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jPanel1.add(mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 210, -1));

        cp.setColumns(20);
        cp.setRows(5);
        jScrollPane1.setViewportView(cp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 550, 90));

        op.setColumns(20);
        op.setRows(5);
        jScrollPane2.setViewportView(op);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 500, 90));

        jButton1.setBackground(new java.awt.Color(66, 33, 26));
        jButton1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 740, 200, 40));

        jButton2.setBackground(new java.awt.Color(66, 33, 26));
        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 740, 180, 40));

        dr.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jPanel1.add(dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 210, -1));

        t.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 210, -1));

        p.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 160, 210, -1));

        ra.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raActionPerformed(evt);
            }
        });
        jPanel1.add(ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 230, 210, -1));

        i.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        jPanel1.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 300, 210, -1));

        d.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 380, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        d.setText("");
        i.setText("");
        la.setText("");
        p.setText("");
        t.setText("");
        s.setText("");
        ra.setText("");
        op.setText("");
        dr.setText("");
        cp.setText("");
        mr.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                if(t.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null," Total Population field is Empty");
        }
        else if(s.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Snow Measured is Empty");
        }
        else if(dr.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Death Rate is Empty");
        }
        else if(mr.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Missing Rate Field is Empty");
        }
        else if(cp.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Community Participation Field is Empty");
        }
          else if(p.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Place Field is Empty");
        }
          else if(ra.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Region Affected Field is Empty");
        }
          else if(i.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Injury Field is Empty");
        }
          else if(la.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"People Mentality Field is Empty");
        }
          else if(op.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Others Field is Empty");
        }
         
         
        JOptionPane.showMessageDialog(rootPane,"SUCCESSFULLY REPORTED");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        con_disaster_frame con=new con_disaster_frame();
        con.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(floodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(floodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(floodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(floodForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new floodForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cp;
    private javax.swing.JTextField d;
    private javax.swing.JTextField dr;
    private javax.swing.JTextField i;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField la;
    private javax.swing.JTextField mr;
    private javax.swing.JTextArea op;
    private javax.swing.JTextField p;
    private javax.swing.JTextField ra;
    private javax.swing.JTextField s;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
