/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ponth
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class formdisaster extends JFrame implements ActionListener{

    /**
     * Creates new form formdisaster
     */
    private final Container c;
    private final JLabel title = null;
    private final JLabel disasterName;
    private final JComboBox dName;
    private JLabel place;
    private JTextField pName;
    private final JCheckBox term;
    private final JButton sub;
    private JButton reset;
    private final JTextArea tout;
    private final JLabel res;
    private JTextArea resadd;
    
    private final String[] disasters={"Cyclone","Drought","Flood","Earthquake","Storm","Tsunami","Volcanic Eruption"};
    public formdisaster() {
        initComponents();
        setTitle("DISASTER FORM");
        setBounds(300,90,900,600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        
        c=getContentPane();
        c.setLayout(new CardLayout());
        
    /*    title =new JLabel("DISASTER FORM");
        title.setFont(new Font("ARIAL",Font.ROMAN_BASELINE,30));
        title.setSize(300,30);
        title.setLocation(300,30);
        c.add(title);*/
        
        disasterName= new JLabel("SELECT DISASTER NAME:");
        disasterName.setFont(new Font("Arial",Font.PLAIN,30));
        disasterName.setSize(100,20);
        disasterName.setLocation(100,100);
        c.add(disasterName);
        
        term = new JCheckBox("Accept Terms And Conditions.");
        term.setFont(new Font("Arial", Font.PLAIN, 15));
        term.setSize(250, 20);
        term.setLocation(150, 400);
     //   term.setLayout(BorderLayout.LINE_END);
        c.add(term);
        
        
        
        sub = new JButton("Submit");
        sub.setFont(new Font("Arial", Font.PLAIN, 15));
        sub.setSize(100, 20);
        sub.setLocation(150, 450);
        sub.addActionListener(this);
        c.add(sub);
        
         tout = new JTextArea();
        tout.setFont(new Font("Arial", Font.PLAIN, 15));
        tout.setSize(300, 400);
        tout.setLocation(500, 100);
        tout.setLineWrap(true);
        tout.setEditable(false);
        c.add(tout);
 
         res = new JLabel("");
        res.setFont(new Font("Arial", Font.PLAIN, 20));
        res.setSize(500, 25);
        res.setLocation(100, 500);
        c.add(res);
        
        dName=new JComboBox(disasters);
        dName.setFont(new Font("Arial",Font.ITALIC,15));
        dName.setSize(100,20);
        dName.setLocation(100,300);
        c.add(dName);
        
     
        
        setVisible(true);
 /*  @Override
        public void actionPerformed(ActionEvent e)
        {
            if(e.getSource()==sub)
            {
                String data="Disaster Name:"+disasterName.getText()+"\n";
             //   String data1;
             res.setText("Entered successsfully");
            }
        }*/
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formdisaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formdisaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formdisaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formdisaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formdisaster().setVisible(true);
            }
        });*/
       formdisaster f=new formdisaster();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       if(e.getSource()==sub)
       {
           String data="DISAStER:"+dName.getSelectedItem()+"\n";
           tout.setText(data);
           tout.setEditable(false);
           res.setText("Entered Sucessfully");
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
