
import com.github.lgooddatepicker.components.TimePicker;
import java.awt.HeadlessException;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ponth
 */
public class lanslide extends javax.swing.JFrame {

    /**
     * Creates new form lanslide
     */
    public lanslide() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Hi");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/disaster ","root","");
            JOptionPane.showMessageDialog(null,"Connected");
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null," Not Connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        P = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        E = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        c = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        D = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        mt = new javax.swing.JTextArea();
        R = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        cp = new javax.swing.JTextArea();
        d = new com.toedter.calendar.JDateChooser();
        i = new com.toedter.components.JSpinField();
        dr = new com.toedter.components.JSpinField();
        mr = new com.toedter.components.JSpinField();
        jPanel5 = new javax.swing.JPanel();
        SUBMIT = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(66, 33, 26));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(66, 0, 0));
        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LAND SLIDE - TERRESTRIAL DISASTER");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1540, -1));

        jButton4.setBackground(new java.awt.Color(66, 33, 26));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circled-chevron-left.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, -1, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1740, 120));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel3.setText("DATE:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 59, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel4.setText("PLACE:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 119, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel5.setText("MISSING:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 251, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel6.setText("DEATH RATE:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 188, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel7.setText("EFFECTS:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 419, -1, -1));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel8.setText("MITIGATION TAKEN:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 328, -1, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel9.setText("INJURED:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 188, -1, -1));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel10.setText("REGIONS AFFECTED:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 119, -1, -1));

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel11.setText("LATITUDE & LONGITUDE");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 59, -1, -1));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel12.setText("CAUSE:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 419, -1, -1));

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel13.setText("COMMUNITY PARTICIPATION:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 328, -1, -1));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel14.setText("DAMAGES:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 251, -1, -1));

        P.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        jPanel4.add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 116, 158, -1));

        E.setColumns(20);
        E.setRows(5);
        jScrollPane1.setViewportView(E);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 358, -1));

        c.setColumns(20);
        c.setRows(5);
        jScrollPane2.setViewportView(c);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 430, 371, -1));

        D.setColumns(20);
        D.setRows(5);
        jScrollPane3.setViewportView(D);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 248, 318, 50));

        mt.setColumns(20);
        mt.setRows(5);
        jScrollPane4.setViewportView(mt);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 318, 60));

        R.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        jPanel4.add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 116, 280, -1));

        cp.setColumns(20);
        cp.setRows(5);
        jScrollPane5.setViewportView(cp);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1226, 328, 318, 65));
        jPanel4.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 59, 167, 33));
        jPanel4.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(1224, 179, 160, 37));
        jPanel4.add(dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 184, 160, 37));
        jPanel4.add(mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 251, 160, 37));

        SUBMIT.setText("SUBMIT");
        SUBMIT.setBackground(new java.awt.Color(66, 33, 26));
        SUBMIT.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        SUBMIT.setForeground(new java.awt.Color(255, 255, 255));
        SUBMIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUBMITMouseClicked(evt);
            }
        });
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });
        jPanel5.add(SUBMIT);

        jButton2.setBackground(new java.awt.Color(66, 33, 26));
        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 550, 70));

        t.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jPanel4.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 60, 280, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 2070, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        con_disaster_frame con=new con_disaster_frame();
        con.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RActionPerformed

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITActionPerformed
        // TODO add your handling code here:
   //     JOptionPane.showMessageDialog(rootPane,"SUCCESSFULLY REPORTED");
         try
       {
          /* Calendar dob = d.getCalendar();
           TimePicker t = new TimePicker();*/
          
           var forName = Class.forName("com.mysql.cj.jdbc.Driver");
        @SuppressWarnings("UnusedAssignment")
        Connection con = null;
                  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/disaster","root","");
               /*catch (SQLException ex) {
                  Logger.getLogger(lanslide.class.getName()).log(Level.SEVERE, null, ex);
              }*/
        //System.out.println("hi");
              java.sql.Statement stmt=con.createStatement();
        
        //insert of data in server
        Date dob = d.getDate();
       SimpleDateFormat sdf = new SimpleDateFormat("");
           @SuppressWarnings("LocalVariableHidesMemberVariable")
        String date = sdf.format(d.getDate());
        String q1="insert into landslide values('" +d.getDate()+"','"+P.getText()+"','" +(int)dr.getValue ()+"','" +(int)mr.getValue()+"','"+mt.getText()+"','"+E.getText()+"','"+t.getText()+"','"+R.getText()+"','" +(int)i.getValue()+"','"+D.getText()+"','"+cp.getText()+"','"+c.getText()+"')";
        
        System.out.println("hi");                                  
        stmt.executeUpdate(q1);
        JOptionPane.showMessageDialog(null,"Inserted");
    }                         
         
    catch(HeadlessException | SQLException e)
    {
        System.out.println(e);
    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(lanslide.class.getName()).log(Level.SEVERE, null, ex);
        }
     
   
    }//GEN-LAST:event_SUBMITActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        d.setCalendar(null);
        P.setText("");
        dr.setValue(0);
        mr.setValue(0);
        mt.setText("");
        E.setText("");
        t.setText("");
        R.setText("");
        i.setValue(0);
        D.setText("");
        cp.setText("");
        c.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SUBMITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUBMITMouseClicked
        // TODO add your handling code here:
          try
       {
           // var forName = Class.forName("com.mysql.cj.jdbc.Driver");
        @SuppressWarnings("UnusedAssignment")
        Connection con = null;
                  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/disaster","root","");
               /*catch (SQLException ex) {
                  Logger.getLogger(lanslide.class.getName()).log(Level.SEVERE, null, ex);
              }*/
        //System.out.println("hi");
              java.sql.Statement stmt=con.createStatement();
        
        //insert of data in server
       Date dob = d.getDate();
        //SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
          // String q = sdf. format(d.getDate());
        String q1="insert into landslide values('" +d.getDate()+"','"+P.getText()+"','" +dr.getValue()+"','" +mr.getValue()+"','"+mt.getText()+"','" +E.getText()+"','" +t.getText()+"','"+R.getText()+"','" +i.getValue()+"','" +D.getText()+"','"+cp.getText()+"','" +c.getText()+"'";
        System.out.println("hi");                                  
        stmt.executeUpdate(q1);
        JOptionPane.showMessageDialog(null,"Inserted");
    }                                              
    catch(HeadlessException | SQLException e)
    {
        System.out.println(e);
    }
    }//GEN-LAST:event_SUBMITMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lanslide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lanslide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lanslide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lanslide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lanslide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea D;
    private javax.swing.JTextArea E;
    private javax.swing.JTextField P;
    private javax.swing.JTextField R;
    private javax.swing.JButton SUBMIT;
    private javax.swing.JTextArea c;
    private javax.swing.JTextArea cp;
    private com.toedter.calendar.JDateChooser d;
    private com.toedter.components.JSpinField dr;
    private com.toedter.components.JSpinField i;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.components.JSpinField mr;
    private javax.swing.JTextArea mt;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
