/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package disastermanagement;

//import java.sql.Connection;

import java.io.File;

//import java.sql.PreparedStatement;
/**
 *
 * @author User
 */
public class official extends javax.swing.JFrame {
    //connection con = null; 
    //PreparedStatement pst = null;
    /**
     * Creates new form official
     */
    public official() {
       // this.con = null;
        initComponents();
            setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        formcontent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        namebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idnobox = new javax.swing.JTextField();
        emailbox = new javax.swing.JTextField();
        mobilebox = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        dptbox = new javax.swing.JComboBox<>();
        idbox = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addbox = new javax.swing.JTextArea();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        logopanel = new javax.swing.JPanel();
        logolabel = new javax.swing.JLabel();
        labelbg_forformconte = new javax.swing.JLabel();
        labelbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setSize(new java.awt.Dimension(1980, 789));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formcontent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel1.setText("REGISTER Form  FOR OFFICIALS");
        formcontent.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 420, 50));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1. Full Name :");
        formcontent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jButton1.setText("Home");
        formcontent.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));
        formcontent.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 270, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2. Department :");
        formcontent.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, 20));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3.ID Proof & No :");
        formcontent.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("4. Address for Communication :");
        formcontent.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("6. Gender :");
        formcontent.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("7. D.O.B :");
        formcontent.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("8.Email ID :");
        formcontent.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Attach any one original proof in .jpeg or .png format");
        formcontent.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("5. Mobile No :");
        formcontent.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, 20));
        formcontent.add(idnobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 170, -1));

        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });
        formcontent.add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 200, 30));

        mobilebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileboxActionPerformed(evt);
            }
        });
        formcontent.add(mobilebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 290, 30));

        jButton2.setText("Attach Document");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        formcontent.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        dptbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Defence", "Fire Service", "HomeGaurd" }));
        dptbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dptboxActionPerformed(evt);
            }
        });
        formcontent.add(dptbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        idbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aadhar card","Driving License", "Pan card", "Voter ID"}));
        formcontent.add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Female");
        formcontent.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        addbox.setColumns(20);
        addbox.setRows(5);
        jScrollPane1.setViewportView(addbox);

        formcontent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 250, 100));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Male");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        formcontent.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, -1, -1));

        jButton3.setText("Back to Login");
        formcontent.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, -1, -1));

        jButton4.setText("Register");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        formcontent.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  "1", "2", "3", "4", "5",
            "6", "7", "8", "9", "10",
            "11", "12", "13", "14", "15",
            "16", "17", "18", "19", "20",
            "21", "22", "23", "24", "25",
            "26", "27", "28", "29", "30","31" }));
formcontent.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));

jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "feb", "Mar", "Apr",
    "May", "Jun", "July", "Aug",
    "Sep", "Oct", "Nov", "Dec" }));
    jComboBox4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox4ActionPerformed(evt);
        }
    });
    formcontent.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1995", "1996", "1997", "1998",
        "1999", "2000", "2001", "2002",
        "2003", "2004", "2005", "2006",
        "2007", "2008", "2009", "2010",
        "2011", "2012", "2013", "2014",
        "2015", "2016", "2017", "2018",
        "2019" }));
formcontent.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, -1, -1));

logopanel.setBackground(new java.awt.Color(204, 174, 248));
logopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

logolabel.setBackground(new java.awt.Color(232, 143, 232));
logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo128x128.png"))); // NOI18N
logolabel.setText("jLabel2");
logopanel.add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 128, 128));

formcontent.add(logopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 128, 128));

labelbg_forformconte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thunder (2).jpg"))); // NOI18N
labelbg_forformconte.setText("jLabel2");
formcontent.add(labelbg_forformconte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1065, 572));

getContentPane().add(formcontent, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 1060, 570));

labelbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/galaxy.jpg"))); // NOI18N
labelbg.setText("jLabel2");
getContentPane().add(labelbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1920, 1140));

pack();
}// </editor-fold>//GEN-END:initComponents

    private void mobileboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileboxActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void dptboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dptboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dptboxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    /*    try{
*                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Management","root","");
                    pst=con.prepareStatement(query);
                    pst.setString(1,namebox.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Registered Successfully")
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Not Registered ")
        }*/
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailboxActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
       /* string fname=namebox.getText();
        if (fname.equals(""))
                {
                    JOptionPane().setDialog("Please enter all Details");
                }*/
    }//GEN-LAST:event_jButton4MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(official.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(official.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(official.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(official.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new official().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addbox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> dptbox;
    private javax.swing.JTextField emailbox;
    private javax.swing.JPanel formcontent;
    private javax.swing.JComboBox<String> idbox;
    private javax.swing.JTextField idnobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelbg;
    private javax.swing.JLabel labelbg_forformconte;
    private javax.swing.JLabel logolabel;
    private javax.swing.JPanel logopanel;
    private javax.swing.JTextField mobilebox;
    private javax.swing.JTextField namebox;
    // End of variables declaration//GEN-END:variables
}
