
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import com.mysql.cj.jdbc.Driver;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author revat
 */
public class OfficialloginForm extends javax.swing.JFrame {

    /**
     * Creates new form OfficialloginForm
     */
    public OfficialloginForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        c.setText(createCaptchaValue());
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Hi");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Oform ","root","");
            JOptionPane.showMessageDialog(null,"Connected");
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null," Not Connected");
        }
    }
    public void clearFields()
    {
        p1.setText("");
        t1.setText("");
        e.setText(null);
        
        createCaptchaValue();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        p1 = new javax.swing.JPasswordField();
        c = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("LOGIN   FORM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(591, 591, 591)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(943, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1880, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("USERNAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 136, 152, 44));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 222, 152, 55));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("CAPTCHA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 318, 152, 57));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("ENTER CAPTCHA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 408, 202, 45));

        t1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 136, 394, 44));

        p1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 229, 394, 41));

        c.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 326, 394, 41));

        e.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 408, 394, 45));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 652, 208, 61));

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 0));
        jButton2.setText("LOGIN");
        jButton2.setToolTipText("");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 652, 233, 61));

        jLabel6.setBackground(new java.awt.Color(255, 102, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("If not a member !  REGISTER NOW");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 535, 331, 45));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-refresh.jpeg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 408, 65, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      //  System.exit(0);
        dispose();
     Home ho=new Home();
     ho.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                if(t1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Username Field is Empty");
            c.setText(createCaptchaValue());
            t1.setText("");
           p1.setText("");
           e.setText("");
        }
        else if(p1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Password Field is Empty");
            c.setText(createCaptchaValue());
            t1.setText("");
           p1.setText("");
           e.setText("");
        }
                else if(e.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Captcha Field is Empty ! Enter It");
            c.setText(createCaptchaValue());
            t1.setText("");
           p1.setText("");
           e.setText("");
           
        }
                  else if(!c.getText().equals(e.getText()))
        {
            JOptionPane.showMessageDialog(null,"INVALID CAPTCHA ! LOGIN FAILED");
            //c.setText("");
            c.setText(createCaptchaValue());
            t1.setText("");
           p1.setText("");
           e.setText("");
        }
           
         /* int db=0;
                try
                {
                    try {
                        Class.forName("com.mysql.cj.jdbc.Driver");
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(OfficialloginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Connection con = null;
                    try {
                        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/registrationform","root","");
                    } catch (SQLException ex) {
                        Logger.getLogger(OfficialloginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Statement stmt = null;
                    try {
                        stmt = con.createStatement();
                    } catch (SQLException ex) {
                        Logger.getLogger(OfficialloginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    ResultSet rs = null;
                    try {
                        rs = (ResultSet) stmt.executeQuery("SELECT * FROM reg");
                    } catch (SQLException ex) {
                        Logger.getLogger(OfficialloginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    while(rs.next())
                    {
                        if(rs.getString(1).equals(t1.getText()) && !rs.getString(2).equals(p1.getText()))
                        {
                            db=1;
                            JOptionPane.showMessageDialog(null,"PASSWORD IS INCORRECT!!");
                            break;
                        }
                        else if(rs.getString(1).equals(t1.getText()) && rs.getString(2).equals(p1.getText()))
                        {
                            db=1;
                            JOptionPane.showMessageDialog(null,"LOGIN SUCCESS!!");
                            break;
                        }
                        else if(!rs.getString(1).equals(t1.getText()) && rs.getString(2).equals(p1.getText()))
                        {
                             db=1;
                            JOptionPane.showMessageDialog(null,"INVALID USERNAME!!");
                            break;
                        }
                    }
                    if(db!=1)
                    {
                        JOptionPane.showMessageDialog(null,"LOGIN FAILED!! Contact Us");
                       
                    }
                     catch(Exception o)
                {   
                    System.out.println(o);
                }*/
                  
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
 try
       {
           var forName = Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Oform","root","");
        //System.out.println("hi");
        Statement stmt=con.createStatement();
        
        //insert of data in server
       if(c.getText().equals(e.getText()))
       {
        var q1="insert into lfo values('" +t1.getText()+"','"+p1.getText()+"','" +c.getText()+"','" +e.getText()+"')";
                                         
        stmt.executeUpdate(q1);
      //   System.out.println("hi"); 
        
       }
       else{
           t1.setText("");
           p1.setText("");
           c.setText("");
           e.setText("");
           createCaptchaValue();
           
       }
           
           
       
    }                                              
    catch(HeadlessException | SQLException e)
    {
        System.out.println(e);
    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(OfficialloginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
 String user=t1.getText();
 String pass=p1.getText();
 if(user.equals("18032")&& pass.equals("18032"))
 {
     dispose();
     JOptionPane.showMessageDialog(null,"Accessed");
     JOptionPane.showMessageDialog(null,"LOGGED IN !");
        
        Off_home off =new Off_home();
        off.setVisible(true);
 }
 else
 {
  /*  dispose();
     Home ho=new Home();
     ho.setVisible(true);*/
     JOptionPane.showMessageDialog(null, "ACESS DENIED!!\nINCORRECT PASSWORD");
   //  JOptionPane.showInternalConfirmDialog(rootPane, "ACCESS DENIED","DENIED", JOptionPane.ERROR_MESSAGE, HEIGHT);
     clearFields();
//createCaptchaValue();}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked
    }
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        /* var rgf = new RegistrationForm();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSED);*/
        // TODO add your handling code here:
              //  RegistrationForm r=new RegistrationForm();
     //   r.show();
     //   dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        c.setText(createCaptchaValue());
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked
    
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked
public static String createCaptchaValue(){
        Random random = new Random();
        int length = 7+(Math.abs(random.nextInt())%3);
        StringBuffer captchaStrBuffer;
        StringBuffer StringBuffer = captchaStrBuffer = new StringBuffer();
        for(int i=0; i<length;i++){
            int baseCharacterNumber = Math.abs(random.nextInt())%62;
            int characterNumber=0;
            if(baseCharacterNumber < 26){
                characterNumber = 65+baseCharacterNumber;
            }
            else if (baseCharacterNumber < 52)
            {
                characterNumber = 48 + (baseCharacterNumber - 26);
            }
            else{
                characterNumber = 48+(baseCharacterNumber - 52);
            }
            captchaStrBuffer.append((char)characterNumber);
        }
        //for(int i=0;i<=6;i++){
          //  char c = characterNumber.charAt(random.nextInt(characterNumber.length()));
            
            
            
        //}
         
        
               return captchaStrBuffer.toString();
              
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfficialloginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfficialloginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfficialloginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfficialloginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OfficialloginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JTextField e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
