
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ponth
 */
public class TORNADO extends javax.swing.JFrame {

    /**
     * Creates new form TORNADO
     */
    public TORNADO() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            //System.out.println("Hi");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/disaster ","root","");
            JOptionPane.showMessageDialog(null,"Connected");
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null," Not Connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        e = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        c = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        da = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        w = new javax.swing.JTextArea();
        ra = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        cp = new javax.swing.JTextArea();
        d = new com.toedter.calendar.JDateChooser();
        i = new com.toedter.components.JSpinField();
        dr = new com.toedter.components.JSpinField();
        mr = new com.toedter.components.JSpinField();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t = new com.github.lgooddatepicker.components.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(66, 33, 26));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(66, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VOLCANIC ERUPTION -TERRESTIAL DISASTER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1540, -1));

        jButton1.setBackground(new java.awt.Color(66, 33, 26));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circled-chevron-left.png"))); // NOI18N
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1648, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel3.setText("DATE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel4.setText("PLACE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel5.setText("MISSING:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel6.setText("DEATH RATE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel7.setText("EFFECTS:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel8.setText("WIDTH OF TORNADO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel9.setText("INJURED:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel10.setText("REGIONS AFFECTED:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel11.setText("TIME:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel12.setText("CAUSE:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, -1, -1));

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel13.setText("COMMUNITY PARTICIPATION:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel14.setText("DAMAGES:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        p.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 230, -1));

        e.setColumns(20);
        e.setRows(5);
        jScrollPane1.setViewportView(e);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 358, -1));

        c.setColumns(20);
        c.setRows(5);
        jScrollPane2.setViewportView(c);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, 371, -1));

        da.setColumns(20);
        da.setRows(5);
        jScrollPane3.setViewportView(da);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 250, 318, 50));

        w.setColumns(20);
        w.setRows(5);
        jScrollPane4.setViewportView(w);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 318, 60));

        ra.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        ra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raActionPerformed(evt);
            }
        });
        jPanel1.add(ra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 110, 158, -1));

        cp.setColumns(20);
        cp.setRows(5);
        jScrollPane5.setViewportView(cp);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 330, 318, 65));
        jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 167, 33));
        jPanel1.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 190, 160, 37));
        jPanel1.add(dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 160, 37));
        jPanel1.add(mr, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 160, 37));

        jButton3.setText("SUBMIT");
        jButton3.setBackground(new java.awt.Color(66, 33, 26));
        jButton3.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton2.setText("CLEAR");
        jButton2.setBackground(new java.awt.Color(66, 33, 26));
        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 550, 50));
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 60, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1700, 688));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed

    private void raActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int spin3=mr.getValue();
        int spin1=i.getValue();
        int spin2=dr.getValue();
      if(spin2==0)
        {
            JOptionPane.showMessageDialog(null," Death Rate field is Empty");
        }
     
      
        else if(p.getText().trim().isEmpty())
                       {
            JOptionPane.showMessageDialog(null,"Place is Empty");
        }
        else if(spin3==0)
        {
            JOptionPane.showMessageDialog(null,"Death Rate is Empty");
        }
        
        else if(cp.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null," Community participation is Empty");
        }
          else if(w.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Width Field is Empty");
        }
          else if(ra.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"region Affected Field is Empty");
        }
          else if(spin1==0)
                {
            JOptionPane.showMessageDialog(null,"Injury Field is Empty");
        }
          else if(da.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Damage Field is Empty");
        }
          else if(c.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Cause Field is Empty");
        }
         else if(e.getText().trim().isEmpty())
                {
            JOptionPane.showMessageDialog(null,"Effects Field is Empty");
        }
        else
        {
        JOptionPane.showMessageDialog(rootPane,"SUCCESSFULLY REPORTED");
                }
      try
       {
          /* Calendar dob = d.getCalendar();
           TimePicker t = new TimePicker();*/
          
           var forName = Class.forName("com.mysql.cj.jdbc.Driver");
        @SuppressWarnings("UnusedAssignment")
        Connection con = null;
                  con = DriverManager.getConnection("jdbc:mysql://localhost:3306/disaster","root","");
               /*catch (SQLException ex) {
                  Logger.getLogger(lanslide.class.getName()).log(Level.SEVERE, null, ex);
              }*/
        //System.out.println("hi");
              java.sql.Statement stmt=con.createStatement();
        
        //insert of data in server
        Date dob = d.getDate();
       SimpleDateFormat sdf = new SimpleDateFormat("");
           @SuppressWarnings("LocalVariableHidesMemberVariable")
        String date = sdf.format(d.getDate());
        String q1="insert into landslide values('" +d.getDate()+"','"+p.getText()+"','" +(int)dr.getValue ()+"','" +(int)mr.getValue()+"','"+w.getText()+"','"+e.getText()+"','"+t.getText()+"','"+ra.getText()+"','" +(int)i.getValue()+"','"+da.getText()+"','"+cp.getText()+"','"+c.getText()+"')";
        
        System.out.println("hi");                                  
        stmt.executeUpdate(q1);
        JOptionPane.showMessageDialog(null,"Inserted");
    }                         
         
    catch(HeadlessException | SQLException e)
    {
        System.out.println(e);
    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(lanslide.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         d.setCalendar(null);
        p.setText("");
        dr.setValue(0);
        mr.setValue(0);
        w.setText("");
        e.setText("");
        t.setText("");
        ra.setText("");
        i.setValue(0);
        da.setText("");
        cp.setText("");
        c.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TORNADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TORNADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TORNADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TORNADO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TORNADO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea c;
    private javax.swing.JTextArea cp;
    private com.toedter.calendar.JDateChooser d;
    private javax.swing.JTextArea da;
    private com.toedter.components.JSpinField dr;
    private javax.swing.JTextArea e;
    private com.toedter.components.JSpinField i;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.components.JSpinField mr;
    private javax.swing.JTextField p;
    private javax.swing.JTextField ra;
    private com.github.lgooddatepicker.components.TimePicker t;
    private javax.swing.JTextArea w;
    // End of variables declaration//GEN-END:variables
}
