

import disastermanagement.selectionpage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class welcomepage extends javax.swing.JFrame {

    /**
     * Creates new form welcomepage
     */
    public welcomepage() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        displaypercent = new javax.swing.JLabel();
        logopanel = new javax.swing.JPanel();
        logolabel = new javax.swing.JLabel();
        adname = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        titilelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 280, 20));

        displaypercent.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        displaypercent.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(displaypercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 60, 20));

        logopanel.setBackground(new java.awt.Color(255, 255, 204));
        logopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo128x128.png"))); // NOI18N
        logopanel.add(logolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 120));

        getContentPane().add(logopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 128, 128));

        adname.setBackground(new java.awt.Color(255, 231, 115));
        adname.setText("By Ajithaa ,Alfeena,Revathi");
        adname.setEditable(false);
        adname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adnameActionPerformed(evt);
            }
        });
        getContentPane().add(adname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/welcome1.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 120, 1930, 960));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titilelabel.setBackground(new java.awt.Color(255, 255, 255));
        titilelabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        titilelabel.setText("          DISASTER MANAGEMENT");
        jPanel1.add(titilelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 780, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 1790, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    welcomepage w=new welcomepage();
        w.setVisible(true);
        try
        {
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(20);
                w.jProgressBar1.setValue(i);
                w.displaypercent.setText(Integer.toString(i)+"%");
                
            }
        }
        catch(Exception e)
        {
            
        }
        
       new Home().setVisible(true);
        w.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adname;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel displaypercent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel logolabel;
    private javax.swing.JPanel logopanel;
    private javax.swing.JLabel titilelabel;
    // End of variables declaration//GEN-END:variables
}
